# Generated by Django 4.0 on 2022-04-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteberry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacoes',
            name='vendaMorango',
            field=models.IntegerField(),
        ),
    ]
